"""
Django settings for uLostIfound project.

Generated by 'django-admin startproject' using Django 5.2.8.
"""
import dj_database_url
import os
from pathlib import Path
from dotenv import load_dotenv # <-- Add this import

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

load_dotenv(BASE_DIR / '.env') # <-- Add this line

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-xqq3qwfpor&gr5(=q@(x$snw55-u&+v(g^l679@ymtqz2qaw3$'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']

# Detect environment early so storage config can branch safely.
IS_RAILWAY_ENV = any(
    os.environ.get(key)
    for key in ['RAILWAY_ENVIRONMENT', 'RAILWAY_PROJECT_ID', 'RAILWAY_PUBLIC_DOMAIN']
)
IS_LOCAL_DEV = DEBUG and not IS_RAILWAY_ENV

# Cloudinary config (used in production). Local dev falls back to filesystem storage.
CLOUDINARY_CLOUD_NAME = os.environ.get('CLOUDINARY_CLOUD_NAME')
CLOUDINARY_API_KEY = os.environ.get('CLOUDINARY_API_KEY')
CLOUDINARY_API_SECRET = os.environ.get('CLOUDINARY_API_SECRET')
USE_CLOUDINARY = (not IS_LOCAL_DEV) and all([CLOUDINARY_CLOUD_NAME, CLOUDINARY_API_KEY, CLOUDINARY_API_SECRET])

# Application definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
    'users',
    'reports',
    'rest_framework',
    'cloudinary_storage',
    'cloudinary',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'

if USE_CLOUDINARY:
    CLOUDINARY_STORAGE = {
        'CLOUD_NAME': CLOUDINARY_CLOUD_NAME,
        'API_KEY': CLOUDINARY_API_KEY,
        'API_SECRET': CLOUDINARY_API_SECRET
    }
    STORAGES = {
        "default": {
            "BACKEND": "cloudinary_storage.storage.MediaCloudinaryStorage",
        },
        "staticfiles": {
            "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
        },
    }
else:
    STORAGES = {
        "default": {
            "BACKEND": "django.core.files.storage.FileSystemStorage",
        },
        "staticfiles": {
            "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
        },
    }

# Database
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# If a DATABASE_URL environment variable exists (like on Railway), use PostgreSQL instead
database_url = os.environ.get("DATABASE_URL")
if database_url:
    DATABASES['default'] = dj_database_url.parse(database_url)

# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',},
]

# Internationalization
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True

# Static files (CSS, JavaScript, Images)
STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Media files (User uploads like avatars, report images)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

AUTH_USER_MODEL = 'users.User'

# --- Custom Authentication Backend ---
AUTHENTICATION_BACKENDS = [
    'users.backends.CustomUserAuthBackend', # Use the custom logic first
    'django.contrib.auth.backends.ModelBackend', # Keep Django's default for safety
]

# ==============================================================================
# CORS & CSRF CONFIGURATION
# ==============================================================================

# 1. CORS Settings (Allow React to communicate with Django)
CORS_ALLOW_CREDENTIALS = True

# Keep frontend origins centralized so CORS and CSRF stay in sync.
FRONTEND_ORIGINS = [
    'https://u-lost-ifound.vercel.app',
    'https://u-lost-ifound-git-russel-andresrobinking-2780s-projects.vercel.app',
    'http://localhost:5173',
    'http://127.0.0.1:5173',
]
CORS_ALLOWED_ORIGINS = FRONTEND_ORIGINS

# 2. CSRF Trusted Origins (required for cross-origin unsafe methods, e.g. login POST)
CSRF_TRUSTED_ORIGINS = [
    'https://ulostifound-production.up.railway.app',
    *FRONTEND_ORIGINS,
]

# 3. Cookie security settings
# Local HTTP development cannot use Secure cookies. Production must use Secure+None.

if IS_LOCAL_DEV:
    CSRF_COOKIE_SAMESITE = 'Lax'
    SESSION_COOKIE_SAMESITE = 'Lax'
    CSRF_COOKIE_SECURE = False
    SESSION_COOKIE_SECURE = False
else:
    CSRF_COOKIE_SAMESITE = 'None'
    SESSION_COOKIE_SAMESITE = 'None'
    CSRF_COOKIE_SECURE = True
    SESSION_COOKIE_SECURE = True

# We use /api/csrf/ JSON endpoint, so frontend doesn't need direct cookie access.
CSRF_COOKIE_HTTPONLY = True

# ==============================================================================
# EMAIL CONFIGURATION
# ==============================================================================
def _env_bool(name, default=False):
    return str(os.environ.get(name, default)).lower() in ('1', 'true', 'yes', 'on')

EMAIL_BACKEND = os.environ.get('EMAIL_BACKEND', 'django.core.mail.backends.smtp.EmailBackend')
EMAIL_HOST = os.environ.get('EMAIL_HOST', 'smtp.gmail.com')
EMAIL_PORT = int(os.environ.get('EMAIL_PORT', '587'))
EMAIL_USE_TLS = _env_bool('EMAIL_USE_TLS', True)
EMAIL_USE_SSL = _env_bool('EMAIL_USE_SSL', False)
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD')
DEFAULT_FROM_EMAIL = os.environ.get('DEFAULT_FROM_EMAIL', EMAIL_HOST_USER or 'no-reply@localhost')
EMAIL_TIMEOUT = int(os.environ.get('EMAIL_TIMEOUT', '20'))

# Resend (HTTP API) configuration
RESEND_API_KEY = (os.environ.get('RESEND_API_KEY') or '').strip() or None
RESEND_FROM_EMAIL = (os.environ.get('RESEND_FROM_EMAIL') or DEFAULT_FROM_EMAIL or '').strip() or None
RESEND_API_URL = os.environ.get('RESEND_API_URL', 'https://api.resend.com/emails')
RESEND_TIMEOUT = int(os.environ.get('RESEND_TIMEOUT', EMAIL_TIMEOUT))
RESEND_USER_AGENT = os.environ.get('RESEND_USER_AGENT', 'uLostIfound/1.0')

# If local dev has no SMTP credentials, use console backend for convenience.
if IS_LOCAL_DEV and not (EMAIL_HOST_USER and EMAIL_HOST_PASSWORD):
    EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
