# Generated by Django 5.2.8 on 2025-11-30 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claim',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Claimed', 'Claimed'), ('Rejected', 'Rejected')], default='Pending', max_length=10),
        ),
    ]
