# Generated by Django 5.2.8 on 2026-01-24 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_alter_claim_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='proof_image',
            field=models.ImageField(blank=True, help_text='Upload an image as proof of ownership.', null=True, upload_to='claim_proofs/'),
        ),
    ]
