# Generated by Django 5.2.8 on 2026-01-24 16:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0005_claim_proof_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visual_score', models.FloatField(default=0, help_text='Image similarity score from CLIP (0-100)')),
                ('text_score', models.FloatField(default=0, help_text='Text/description similarity score (0-100)')),
                ('match_score', models.FloatField(default=0, help_text='Combined overall match score (0-100)')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=10)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('lost_reporter_notified', models.BooleanField(default=False)),
                ('found_reporter_notified', models.BooleanField(default=False)),
                ('found_report', models.ForeignKey(limit_choices_to={'type': 'Found'}, on_delete=django.db.models.deletion.CASCADE, related_name='found_matches', to='reports.report')),
                ('lost_report', models.ForeignKey(limit_choices_to={'type': 'Lost'}, on_delete=django.db.models.deletion.CASCADE, related_name='lost_matches', to='reports.report')),
            ],
            options={
                'verbose_name': 'AI Match',
                'verbose_name_plural': 'AI Matches',
                'ordering': ['-match_score', '-date_created'],
                'unique_together': {('lost_report', 'found_report')},
            },
        ),
    ]
