# Generated by Django 6.0.2 on 2026-02-09 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0006_aimatch'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
