# Generated by Django 6.0.2 on 2026-02-18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0007_claim_rejection_reason'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='claim',
            constraint=models.UniqueConstraint(
                fields=('report', 'claimant'),
                name='unique_claim_per_user_per_report',
            ),
        ),
    ]

