# Generated by Django 6.0.2 on 2026-03-03 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0009_foundclaimrecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Verified', 'Verified'), ('Matched', 'Matched'), ('Claimed', 'Claimed'), ('Rejected', 'Rejected')], default='Pending', max_length=10),
        ),
    ]
