# Generated by Django 6.0.2 on 2026-03-04 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0010_alter_report_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aimatch",
            name="visual_score",
            field=models.FloatField(
                default=0,
                help_text="Image similarity score from TensorFlow Lite MobileNetV3 (0-100)",
            ),
        ),
    ]
